/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view.pessoa;

import java.awt.Dimension;
import java.awt.event.KeyEvent;
import java.util.List;
import model.bean.principal.Pessoa;
import model.bean.principal.PessoaTipo;
import model.dao.principal.PessoaDAO;
import model.jtable.PessoaJTableModel;
import static ouroboros.Constants.CELL_RENDERER_ALIGN_RIGHT;
import static ouroboros.Ouroboros.MAIN_VIEW;

/**
 *
 * @author ivand
 */
public class PessoaPesquisaView extends javax.swing.JDialog {

    //private static PessoaPesquisaView clientePesquisaView;
    PessoaJTableModel pessoaJTableModel = new PessoaJTableModel();
    PessoaDAO pessoaDAO = new PessoaDAO();

    List<Pessoa> pessoas;
    PessoaTipo pessoaTipo;
    
    Pessoa pessoa = null;

    /**
     * Creates new form PessoaPesquisa
     * @param pessoaTipo
     */
    public PessoaPesquisaView(PessoaTipo pessoaTipo) {
        initComponents();

        this.pessoaTipo = pessoaTipo;
        
        formatarTabela();
        carregarTabela();
        
        this.setLocationRelativeTo(MAIN_VIEW);
        this.setModal(true);
        this.setVisible(true);
    }
    
    public Pessoa getPessoa(){
        return pessoa;
    }
    
    private void formatarTabela() {
        tblPessoa.setModel(pessoaJTableModel);

        tblPessoa.setRowHeight(24);
        tblPessoa.setIntercellSpacing(new Dimension(10, 10));
        //id
        tblPessoa.getColumnModel().getColumn(0).setPreferredWidth(60);
        tblPessoa.getColumnModel().getColumn(0).setCellRenderer(CELL_RENDERER_ALIGN_RIGHT);
        //nome
        tblPessoa.getColumnModel().getColumn(1).setPreferredWidth(800);
        //descrição
        tblPessoa.getColumnModel().getColumn(2).setPreferredWidth(400);
        //valor
        tblPessoa.getColumnModel().getColumn(3).setPreferredWidth(120);
        tblPessoa.getColumnModel().getColumn(3).setCellRenderer(CELL_RENDERER_ALIGN_RIGHT);
        //código
        tblPessoa.getColumnModel().getColumn(4).setPreferredWidth(200);
        //unidade comercial
        tblPessoa.getColumnModel().getColumn(5).setPreferredWidth(120);
    }
    
    private void carregarTabela() {
        String buscaRapida = txtBuscaRapida.getText();

        pessoas = pessoaDAO.findByNome(buscaRapida, pessoaTipo);
        

        pessoaJTableModel.clear();
        pessoaJTableModel.addList(pessoas);
        
        if(tblPessoa.getRowCount() > 0){
            tblPessoa.setRowSelectionInterval(0, 0);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txtBuscaRapida = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblPessoa = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();

        setTitle("Pesquisar Pessoa");

        txtBuscaRapida.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        txtBuscaRapida.setToolTipText("");
        txtBuscaRapida.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtBuscaRapidaKeyReleased(evt);
            }
        });

        tblPessoa.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tblPessoa.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                tblPessoaFocusGained(evt);
            }
        });
        tblPessoa.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblPessoaMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblPessoa);

        jLabel1.setForeground(java.awt.Color.blue);
        jLabel1.setText("Rolar: PageUp e PageDown | Confirmar: Enter | Cancelar: Esc");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(txtBuscaRapida, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 980, Short.MAX_VALUE))
                        .addContainerGap())))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(txtBuscaRapida, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 402, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel1)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtBuscaRapidaKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtBuscaRapidaKeyReleased
        int index;
        switch (evt.getKeyCode()) {
            case KeyEvent.VK_ESCAPE:
                pessoa = null;
                dispose();
                break;
            case KeyEvent.VK_ENTER:
                if(tblPessoa.getSelectedRow() != -1) {
                    pessoa = pessoaJTableModel.getRow(tblPessoa.getSelectedRow());
                    dispose();
                }
                break;
            case KeyEvent.VK_DOWN:
                index = tblPessoa.getSelectedRow() + 1;
                if (index < tblPessoa.getRowCount()) {
                    tblPessoa.setRowSelectionInterval(index, index);
                    tblPessoa.scrollRectToVisible(tblPessoa.getCellRect(index, 0, true));
                }
                break;
            case KeyEvent.VK_UP:
                index = tblPessoa.getSelectedRow() - 1;
                if (index > -1) {
                    tblPessoa.setRowSelectionInterval(index, index);
                    tblPessoa.scrollRectToVisible(tblPessoa.getCellRect(index, 0, true));
                }
                break;
            case KeyEvent.VK_PAGE_DOWN:
                index = tblPessoa.getSelectedRow() + 10;
                if (index > tblPessoa.getRowCount() -1) {
                    index = tblPessoa.getRowCount() -1;
                }
                tblPessoa.setRowSelectionInterval(index, index);
                tblPessoa.scrollRectToVisible(tblPessoa.getCellRect(index, 0, true));
                break;
            case KeyEvent.VK_PAGE_UP:
                index = tblPessoa.getSelectedRow() - 10;
                if (index < 0) {
                    index = 0;
                }
                tblPessoa.setRowSelectionInterval(index, index);
                tblPessoa.scrollRectToVisible(tblPessoa.getCellRect(index, 0, true));
                break;
            default:
                carregarTabela();
        }
    }//GEN-LAST:event_txtBuscaRapidaKeyReleased

    private void tblPessoaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblPessoaMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_tblPessoaMouseClicked

    private void tblPessoaFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_tblPessoaFocusGained
        txtBuscaRapida.requestFocus();
    }//GEN-LAST:event_tblPessoaFocusGained


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblPessoa;
    private javax.swing.JTextField txtBuscaRapida;
    // End of variables declaration//GEN-END:variables

    
}
