/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view.endereco;

import java.awt.Dimension;
import java.awt.event.KeyEvent;
import java.util.List;
import model.mysql.bean.endereco.Endereco;
import model.mysql.dao.endereco.EnderecoDAO;
import model.jtable.endereco.EnderecoJTableModel;
import static ouroboros.Constants.CELL_RENDERER_ALIGN_RIGHT;
import static ouroboros.Ouroboros.MAIN_VIEW;

/**
 *
 * @author ivand
 */
public class EnderecoPesquisaView extends javax.swing.JDialog {

    //private static EnderecoPesquisaView enderecoView;
    EnderecoJTableModel enderecoJTableModel = new EnderecoJTableModel();
    EnderecoDAO enderecoDAO = new EnderecoDAO();

    List<Endereco> enderecos;
    
    Endereco endereco = null;

    public EnderecoPesquisaView() {
        super(MAIN_VIEW, true);
        initComponents();

        formatarTabela();

        //carregarTabela();
        
        this.setLocationRelativeTo(MAIN_VIEW);
        this.setVisible(true);
        
    }
    
    public EnderecoPesquisaView(String buscar) {
        super(MAIN_VIEW, true);
        initComponents();

        formatarTabela();

        txtBuscaRapida.setText(buscar);
        carregarTabela();
        
        this.setLocationRelativeTo(MAIN_VIEW);
        this.setVisible(true);
    }
    
    
    public Endereco getEndereco(){
        return endereco;
    }
    
    private void carregarTabela() {
        String buscaRapida = txtBuscaRapida.getText();

        enderecos = enderecoDAO.findByCriteria(buscaRapida);

        enderecoJTableModel.clear();
        enderecoJTableModel.addList(enderecos);
        
        if(tblEndereco.getRowCount() > 0){
            tblEndereco.setRowSelectionInterval(0, 0);
        }
    }
    
    private void formatarTabela() {
        tblEndereco.setModel(enderecoJTableModel);

        tblEndereco.setRowHeight(24);
        tblEndereco.setIntercellSpacing(new Dimension(10, 10));

        tblEndereco.getColumn("Endereço").setPreferredWidth(400);
        
        tblEndereco.getColumn("Bairro").setPreferredWidth(250);
        
        tblEndereco.getColumn("Cidade").setPreferredWidth(250);
        
        tblEndereco.getColumn("CEP").setPreferredWidth(100);
        tblEndereco.getColumn("CEP").setCellRenderer(CELL_RENDERER_ALIGN_RIGHT);

    }
    
    private void confirmar() {
        endereco = enderecoJTableModel.getRow(tblEndereco.getSelectedRow());
        dispose();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txtBuscaRapida = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblEndereco = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();

        setTitle("Pesquisar Endereço");

        txtBuscaRapida.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        txtBuscaRapida.setToolTipText("");
        txtBuscaRapida.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtBuscaRapidaKeyReleased(evt);
            }
        });

        tblEndereco.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tblEndereco.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                tblEnderecoFocusGained(evt);
            }
        });
        tblEndereco.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblEnderecoMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblEndereco);

        jLabel1.setForeground(java.awt.Color.blue);
        jLabel1.setText("Rolar: PageUp e PageDown | Confirmar: Enter | Cancelar: Esc");

        jLabel2.setForeground(java.awt.Color.red);
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel2.setText("Consulta sensível aos acentos. Resultado limitado à 100 registros devido ao grande volume de dados");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 573, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(txtBuscaRapida)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 964, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(txtBuscaRapida, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 402, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtBuscaRapidaKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtBuscaRapidaKeyReleased
        int index;
        switch (evt.getKeyCode()) {
            case KeyEvent.VK_ESCAPE:
                endereco = null;
                dispose();
                break;
            case KeyEvent.VK_ENTER:
                confirmar();
                break;
            case KeyEvent.VK_DOWN:
                index = tblEndereco.getSelectedRow() + 1;
                if (index < tblEndereco.getRowCount()) {
                    tblEndereco.setRowSelectionInterval(index, index);
                    tblEndereco.scrollRectToVisible(tblEndereco.getCellRect(index, 0, true));
                }
                break;
            case KeyEvent.VK_UP:
                index = tblEndereco.getSelectedRow() - 1;
                if (index > -1) {
                    tblEndereco.setRowSelectionInterval(index, index);
                    tblEndereco.scrollRectToVisible(tblEndereco.getCellRect(index, 0, true));
                }
                break;
            case KeyEvent.VK_PAGE_DOWN:
                index = tblEndereco.getSelectedRow() + 10;
                if (index > tblEndereco.getRowCount() -1) {
                    index = tblEndereco.getRowCount() -1;
                }
                tblEndereco.setRowSelectionInterval(index, index);
                tblEndereco.scrollRectToVisible(tblEndereco.getCellRect(index, 0, true));
                break;
            case KeyEvent.VK_PAGE_UP:
                index = tblEndereco.getSelectedRow() - 10;
                if (index < 0) {
                    index = 0;
                }
                tblEndereco.setRowSelectionInterval(index, index);
                tblEndereco.scrollRectToVisible(tblEndereco.getCellRect(index, 0, true));
                break;
            default:
                carregarTabela();
        }
    }//GEN-LAST:event_txtBuscaRapidaKeyReleased

    private void tblEnderecoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblEnderecoMouseClicked
        if(evt.getClickCount() == 2) {
            confirmar();
        }
    }//GEN-LAST:event_tblEnderecoMouseClicked

    private void tblEnderecoFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_tblEnderecoFocusGained
        txtBuscaRapida.requestFocus();
    }//GEN-LAST:event_tblEnderecoFocusGained


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblEndereco;
    private javax.swing.JTextField txtBuscaRapida;
    // End of variables declaration//GEN-END:variables

    
}
