/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import view.documentoSaida.item.VendaView;
import javax.swing.plaf.basic.BasicInternalFrameUI;
import model.jtable.documento.OSTransporteListaJTableModel;
import model.mysql.bean.principal.documento.OSTransporte;
import model.mysql.bean.principal.documento.Venda;
import model.mysql.bean.principal.documento.VendaTipo;
import ouroboros.Ouroboros;
import static ouroboros.Ouroboros.MENU_MIN_WIDTH;
import static ouroboros.Ouroboros.SCREEN_HEIGHT;
import view.sistema.ConfguracaoSistema;
import static ouroboros.Ouroboros.MAIN_VIEW;
import util.entities.DocumentoUtil;
import view.documentoEntrada.DocumentoEntradaListaView;
import view.financeiro.FinanceiroContainerView;
import view.funcionario.FuncionarioListaView;
import view.pessoa.PessoaGeralContainerView;
import view.catalogo.geral.ProdutoGeralContainerView;
import view.sistema.BackupView;
import view.usuario.UsuarioListaView;
import view.documentoEntrada.DocumentoEntradaView;
import view.documentoSaida.EscolherTipoOrcamento;
import view.osTransporte.OSTransporteView;
import view.documentoSaida.geral.VendaGeralContainerView;
import view.documentoSaida.geral.VendaPorFichaView;
import view.osTransporte.OstListaView;
import view.veiculo.VeiculoListaView;

/**
 *
 * @author ivand
 */
public class MainMenuView extends javax.swing.JInternalFrame {
    
    
    /**
     * Creates new form MainMenuView
     */
    public MainMenuView() {
        //set apearence
        ((BasicInternalFrameUI)this.getUI()).setNorthPane(null);
        this.setBorder(null);
        this.setBounds(0, 0, MENU_MIN_WIDTH, SCREEN_HEIGHT);
        
        
        
        initComponents();
        
        //btnDocumentosEntrada.setVisible(false);
        //btnCompra.setVisible(false);
    }
    
    public void setBotoes() {
        btnVeiculos.setVisible(Ouroboros.VEICULO_HABILITAR);
        
        btnOSsTransporte.setVisible(Ouroboros.OST_HABILITAR);
        btnOSTransporte.setVisible(Ouroboros.OST_HABILITAR);
        
        btnVendaPorFicha.setVisible(Ouroboros.VENDA_POR_FICHA_HABILITAR);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnOrcamento = new javax.swing.JButton();
        btnMesas = new javax.swing.JButton();
        btnDocumentosSaida = new javax.swing.JButton();
        btnProdutos1 = new javax.swing.JButton();
        btnFinanceiro = new javax.swing.JButton();
        btnSistema = new javax.swing.JButton();
        btnPessoas = new javax.swing.JButton();
        btnUsuarios = new javax.swing.JButton();
        btnBackup = new javax.swing.JButton();
        btnVenda = new javax.swing.JButton();
        btnOrdemDeServico = new javax.swing.JButton();
        btnCompra = new javax.swing.JButton();
        btnFuncionarios = new javax.swing.JButton();
        btnDocumentosEntrada = new javax.swing.JButton();
        btnVeiculos = new javax.swing.JButton();
        btnDelivery = new javax.swing.JButton();
        btnOSTransporte = new javax.swing.JButton();
        btnOSsTransporte = new javax.swing.JButton();
        btnVendaPorFicha = new javax.swing.JButton();

        setBackground(javax.swing.UIManager.getDefaults().getColor("Button.darkShadow"));
        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                formMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                formMouseExited(evt);
            }
        });
        addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentShown(java.awt.event.ComponentEvent evt) {
                formComponentShown(evt);
            }
        });

        btnOrcamento.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        btnOrcamento.setIcon(new javax.swing.ImageIcon(getClass().getResource("/res/img/folder_page_white.png"))); // NOI18N
        btnOrcamento.setText("Orçamento");
        btnOrcamento.setContentAreaFilled(false);
        btnOrcamento.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btnOrcamento.setIconTextGap(20);
        btnOrcamento.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnOrcamentoMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnOrcamentoMouseExited(evt);
            }
        });
        btnOrcamento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnOrcamentoActionPerformed(evt);
            }
        });

        btnMesas.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        btnMesas.setIcon(new javax.swing.ImageIcon(getClass().getResource("/res/img/color_swatch.png"))); // NOI18N
        btnMesas.setText("Comandas");
        btnMesas.setContentAreaFilled(false);
        btnMesas.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btnMesas.setIconTextGap(20);
        btnMesas.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnMesasMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnMesasMouseExited(evt);
            }
        });
        btnMesas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMesasActionPerformed(evt);
            }
        });

        btnDocumentosSaida.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        btnDocumentosSaida.setIcon(new javax.swing.ImageIcon(getClass().getResource("/res/img/icon/icons8-paid-20.png"))); // NOI18N
        btnDocumentosSaida.setText("Documentos de Saída");
        btnDocumentosSaida.setContentAreaFilled(false);
        btnDocumentosSaida.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btnDocumentosSaida.setIconTextGap(20);
        btnDocumentosSaida.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnDocumentosSaidaMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnDocumentosSaidaMouseExited(evt);
            }
        });
        btnDocumentosSaida.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDocumentosSaidaActionPerformed(evt);
            }
        });

        btnProdutos1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        btnProdutos1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/res/img/package.png"))); // NOI18N
        btnProdutos1.setText("Produtos e Serviços");
        btnProdutos1.setContentAreaFilled(false);
        btnProdutos1.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btnProdutos1.setIconTextGap(20);
        btnProdutos1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnProdutos1MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnProdutos1MouseExited(evt);
            }
        });
        btnProdutos1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnProdutos1ActionPerformed(evt);
            }
        });

        btnFinanceiro.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        btnFinanceiro.setIcon(new javax.swing.ImageIcon(getClass().getResource("/res/img/icon/icons8-profit-20.png"))); // NOI18N
        btnFinanceiro.setText("Financeiro");
        btnFinanceiro.setContentAreaFilled(false);
        btnFinanceiro.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btnFinanceiro.setIconTextGap(20);
        btnFinanceiro.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnFinanceiroMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnFinanceiroMouseExited(evt);
            }
        });
        btnFinanceiro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFinanceiroActionPerformed(evt);
            }
        });

        btnSistema.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        btnSistema.setIcon(new javax.swing.ImageIcon(getClass().getResource("/res/img/cog.png"))); // NOI18N
        btnSistema.setText("Sistema");
        btnSistema.setContentAreaFilled(false);
        btnSistema.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btnSistema.setIconTextGap(20);
        btnSistema.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnSistemaMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnSistemaMouseExited(evt);
            }
        });
        btnSistema.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSistemaActionPerformed(evt);
            }
        });

        btnPessoas.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        btnPessoas.setIcon(new javax.swing.ImageIcon(getClass().getResource("/res/img/user.png"))); // NOI18N
        btnPessoas.setText("Clientes e Fornecedores");
        btnPessoas.setContentAreaFilled(false);
        btnPessoas.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btnPessoas.setIconTextGap(20);
        btnPessoas.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnPessoasMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnPessoasMouseExited(evt);
            }
        });
        btnPessoas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPessoasActionPerformed(evt);
            }
        });

        btnUsuarios.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        btnUsuarios.setIcon(new javax.swing.ImageIcon(getClass().getResource("/res/img/key.png"))); // NOI18N
        btnUsuarios.setText("Usuários");
        btnUsuarios.setContentAreaFilled(false);
        btnUsuarios.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btnUsuarios.setIconTextGap(20);
        btnUsuarios.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnUsuariosMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnUsuariosMouseExited(evt);
            }
        });
        btnUsuarios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUsuariosActionPerformed(evt);
            }
        });

        btnBackup.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        btnBackup.setIcon(new javax.swing.ImageIcon(getClass().getResource("/res/img/disk.png"))); // NOI18N
        btnBackup.setText("Faça Backup diariamente!");
        btnBackup.setContentAreaFilled(false);
        btnBackup.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btnBackup.setIconTextGap(20);
        btnBackup.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnBackupMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnBackupMouseExited(evt);
            }
        });
        btnBackup.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackupActionPerformed(evt);
            }
        });

        btnVenda.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        btnVenda.setIcon(new javax.swing.ImageIcon(getClass().getResource("/res/img/basket.png"))); // NOI18N
        btnVenda.setText("Venda");
        btnVenda.setContentAreaFilled(false);
        btnVenda.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btnVenda.setIconTextGap(20);
        btnVenda.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnVendaMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnVendaMouseExited(evt);
            }
        });
        btnVenda.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVendaActionPerformed(evt);
            }
        });

        btnOrdemDeServico.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        btnOrdemDeServico.setIcon(new javax.swing.ImageIcon(getClass().getResource("/res/img/icon/icons8-engineer-symbol-20.png"))); // NOI18N
        btnOrdemDeServico.setText("Ordem de Serviço");
        btnOrdemDeServico.setContentAreaFilled(false);
        btnOrdemDeServico.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btnOrdemDeServico.setIconTextGap(20);
        btnOrdemDeServico.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnOrdemDeServicoMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnOrdemDeServicoMouseExited(evt);
            }
        });
        btnOrdemDeServico.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnOrdemDeServicoActionPerformed(evt);
            }
        });

        btnCompra.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        btnCompra.setIcon(new javax.swing.ImageIcon(getClass().getResource("/res/img/lorry.png"))); // NOI18N
        btnCompra.setText("Compra");
        btnCompra.setContentAreaFilled(false);
        btnCompra.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btnCompra.setIconTextGap(20);
        btnCompra.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnCompraMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnCompraMouseExited(evt);
            }
        });
        btnCompra.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCompraActionPerformed(evt);
            }
        });

        btnFuncionarios.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        btnFuncionarios.setIcon(new javax.swing.ImageIcon(getClass().getResource("/res/img/user_red.png"))); // NOI18N
        btnFuncionarios.setText("Funcionários");
        btnFuncionarios.setContentAreaFilled(false);
        btnFuncionarios.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btnFuncionarios.setIconTextGap(20);
        btnFuncionarios.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnFuncionariosMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnFuncionariosMouseExited(evt);
            }
        });
        btnFuncionarios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFuncionariosActionPerformed(evt);
            }
        });

        btnDocumentosEntrada.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        btnDocumentosEntrada.setIcon(new javax.swing.ImageIcon(getClass().getResource("/res/img/icon/icons8-shopping-basket-20.png"))); // NOI18N
        btnDocumentosEntrada.setText("Documentos de Entrada");
        btnDocumentosEntrada.setContentAreaFilled(false);
        btnDocumentosEntrada.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btnDocumentosEntrada.setIconTextGap(20);
        btnDocumentosEntrada.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnDocumentosEntradaMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnDocumentosEntradaMouseExited(evt);
            }
        });
        btnDocumentosEntrada.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDocumentosEntradaActionPerformed(evt);
            }
        });

        btnVeiculos.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        btnVeiculos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/res/img/icon/icons8-car-20.png"))); // NOI18N
        btnVeiculos.setText("Veículos");
        btnVeiculos.setContentAreaFilled(false);
        btnVeiculos.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btnVeiculos.setIconTextGap(20);
        btnVeiculos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnVeiculosMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnVeiculosMouseExited(evt);
            }
        });
        btnVeiculos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVeiculosActionPerformed(evt);
            }
        });

        btnDelivery.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        btnDelivery.setIcon(new javax.swing.ImageIcon(getClass().getResource("/res/img/icon/icons8-scooter-20.png"))); // NOI18N
        btnDelivery.setText("Delivery");
        btnDelivery.setContentAreaFilled(false);
        btnDelivery.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btnDelivery.setIconTextGap(20);
        btnDelivery.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnDeliveryMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnDeliveryMouseExited(evt);
            }
        });
        btnDelivery.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeliveryActionPerformed(evt);
            }
        });

        btnOSTransporte.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        btnOSTransporte.setIcon(new javax.swing.ImageIcon(getClass().getResource("/res/img/icon/icons8-truck-20.png"))); // NOI18N
        btnOSTransporte.setText("OS Transporte");
        btnOSTransporte.setContentAreaFilled(false);
        btnOSTransporte.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btnOSTransporte.setIconTextGap(20);
        btnOSTransporte.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnOSTransporteMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnOSTransporteMouseExited(evt);
            }
        });
        btnOSTransporte.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnOSTransporteActionPerformed(evt);
            }
        });

        btnOSsTransporte.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        btnOSsTransporte.setIcon(new javax.swing.ImageIcon(getClass().getResource("/res/img/icon/icons8-truck-20.png"))); // NOI18N
        btnOSsTransporte.setText("Documentos de Transporte");
        btnOSsTransporte.setContentAreaFilled(false);
        btnOSsTransporte.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btnOSsTransporte.setIconTextGap(20);
        btnOSsTransporte.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnOSsTransporteMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnOSsTransporteMouseExited(evt);
            }
        });
        btnOSsTransporte.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnOSsTransporteActionPerformed(evt);
            }
        });

        btnVendaPorFicha.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        btnVendaPorFicha.setIcon(new javax.swing.ImageIcon(getClass().getResource("/res/img/icon/icons8-ticket-20.png"))); // NOI18N
        btnVendaPorFicha.setText("Venda por Ficha");
        btnVendaPorFicha.setContentAreaFilled(false);
        btnVendaPorFicha.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btnVendaPorFicha.setIconTextGap(20);
        btnVendaPorFicha.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnVendaPorFichaMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnVendaPorFichaMouseExited(evt);
            }
        });
        btnVendaPorFicha.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVendaPorFichaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(btnProdutos1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(btnFinanceiro, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(btnSistema, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(btnPessoas, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(btnUsuarios, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(btnBackup, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(btnVenda, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(btnOrdemDeServico, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(btnFuncionarios, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(btnDocumentosSaida, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(btnOrcamento, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(btnMesas, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(btnDocumentosEntrada, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(btnCompra, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(btnVeiculos, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(btnDelivery, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(btnOSTransporte, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(btnOSsTransporte, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(btnVendaPorFicha, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(btnDocumentosSaida)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnOrcamento)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnVenda)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnOrdemDeServico)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnDelivery)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnMesas)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnVendaPorFicha)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnOSsTransporte)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnOSTransporte)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnDocumentosEntrada)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnCompra)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnProdutos1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnFinanceiro)
                .addGap(4, 4, 4)
                .addComponent(btnPessoas)
                .addGap(4, 4, 4)
                .addComponent(btnFuncionarios)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnVeiculos)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnSistema)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnUsuarios)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnBackup)
                .addContainerGap(48, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_formMouseEntered
        this.toFront();
    }//GEN-LAST:event_formMouseEntered

    private void formMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_formMouseExited
        this.toBack();
    }//GEN-LAST:event_formMouseExited

    private void btnOrcamentoMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnOrcamentoMouseEntered
        formMouseEntered(evt);
    }//GEN-LAST:event_btnOrcamentoMouseEntered

    private void btnOrcamentoMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnOrcamentoMouseExited
        formMouseExited(evt);
    }//GEN-LAST:event_btnOrcamentoMouseExited

    private void btnMesasMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnMesasMouseEntered
        formMouseEntered(evt);
    }//GEN-LAST:event_btnMesasMouseEntered

    private void btnMesasMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnMesasMouseExited
        formMouseExited(evt);
    }//GEN-LAST:event_btnMesasMouseExited

    private void btnDocumentosSaidaMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnDocumentosSaidaMouseEntered
        formMouseEntered(evt);
    }//GEN-LAST:event_btnDocumentosSaidaMouseEntered

    private void btnDocumentosSaidaMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnDocumentosSaidaMouseExited
        formMouseExited(evt);
    }//GEN-LAST:event_btnDocumentosSaidaMouseExited

    private void formComponentShown(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_formComponentShown
        
    }//GEN-LAST:event_formComponentShown

    private void btnOrcamentoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnOrcamentoActionPerformed
        EscolherTipoOrcamento escolherTipoOrcamento = new EscolherTipoOrcamento();
    }//GEN-LAST:event_btnOrcamentoActionPerformed

    private void btnDocumentosSaidaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDocumentosSaidaActionPerformed
        MAIN_VIEW.addView(VendaGeralContainerView.getSingleInstance());
    }//GEN-LAST:event_btnDocumentosSaidaActionPerformed

    private void btnMesasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMesasActionPerformed
        //MAIN_VIEW.addView(ComandasLadrilhoView.getSingleInstance());
        MAIN_VIEW.addView(DocumentoUtil.exibirComandas());
    }//GEN-LAST:event_btnMesasActionPerformed

    private void btnProdutos1MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnProdutos1MouseEntered
        formMouseEntered(evt);
    }//GEN-LAST:event_btnProdutos1MouseEntered

    private void btnProdutos1MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnProdutos1MouseExited
        formMouseExited(evt);
    }//GEN-LAST:event_btnProdutos1MouseExited

    private void btnProdutos1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnProdutos1ActionPerformed
        MAIN_VIEW.addView(ProdutoGeralContainerView.getSingleInstance());
    }//GEN-LAST:event_btnProdutos1ActionPerformed

    private void btnFinanceiroMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnFinanceiroMouseEntered
        formMouseEntered(evt);
    }//GEN-LAST:event_btnFinanceiroMouseEntered

    private void btnFinanceiroMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnFinanceiroMouseExited
        formMouseExited(evt);
    }//GEN-LAST:event_btnFinanceiroMouseExited

    private void btnFinanceiroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFinanceiroActionPerformed
        MAIN_VIEW.addView(FinanceiroContainerView.getSingleInstance());
    }//GEN-LAST:event_btnFinanceiroActionPerformed

    private void btnSistemaMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnSistemaMouseEntered
        formMouseEntered(evt);
    }//GEN-LAST:event_btnSistemaMouseEntered

    private void btnSistemaMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnSistemaMouseExited
        formMouseExited(evt);
    }//GEN-LAST:event_btnSistemaMouseExited

    private void btnSistemaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSistemaActionPerformed
        MAIN_VIEW.addView(ConfguracaoSistema.getSingleInstance());
    }//GEN-LAST:event_btnSistemaActionPerformed

    private void btnPessoasMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnPessoasMouseEntered
        formMouseEntered(evt);
    }//GEN-LAST:event_btnPessoasMouseEntered

    private void btnPessoasMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnPessoasMouseExited
        formMouseExited(evt);
    }//GEN-LAST:event_btnPessoasMouseExited

    private void btnPessoasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPessoasActionPerformed
        MAIN_VIEW.addView(PessoaGeralContainerView.getSingleInstance());
    }//GEN-LAST:event_btnPessoasActionPerformed

    private void btnUsuariosMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnUsuariosMouseEntered
        formMouseEntered(evt);
    }//GEN-LAST:event_btnUsuariosMouseEntered

    private void btnUsuariosMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnUsuariosMouseExited
        formMouseExited(evt);
    }//GEN-LAST:event_btnUsuariosMouseExited

    private void btnUsuariosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUsuariosActionPerformed
        MAIN_VIEW.addView(UsuarioListaView.getSingleInstance());
    }//GEN-LAST:event_btnUsuariosActionPerformed

    private void btnBackupMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnBackupMouseEntered
        formMouseEntered(evt);
    }//GEN-LAST:event_btnBackupMouseEntered

    private void btnBackupMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnBackupMouseExited
        formMouseExited(evt);
    }//GEN-LAST:event_btnBackupMouseExited

    private void btnBackupActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackupActionPerformed
        BackupView b = new BackupView();
    }//GEN-LAST:event_btnBackupActionPerformed

    private void btnVendaMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnVendaMouseEntered
        formMouseEntered(evt);
    }//GEN-LAST:event_btnVendaMouseEntered

    private void btnVendaMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnVendaMouseExited
        formMouseExited(evt);
    }//GEN-LAST:event_btnVendaMouseExited

    private void btnVendaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVendaActionPerformed
        MAIN_VIEW.addView(VendaView.getInstance(new Venda(VendaTipo.VENDA)));
    }//GEN-LAST:event_btnVendaActionPerformed

    private void btnOrdemDeServicoMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnOrdemDeServicoMouseEntered
        formMouseEntered(evt);
    }//GEN-LAST:event_btnOrdemDeServicoMouseEntered

    private void btnOrdemDeServicoMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnOrdemDeServicoMouseExited
        formMouseExited(evt);
    }//GEN-LAST:event_btnOrdemDeServicoMouseExited

    private void btnOrdemDeServicoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnOrdemDeServicoActionPerformed
        MAIN_VIEW.addView(VendaView.getInstance(new Venda(VendaTipo.ORDEM_DE_SERVICO)));
    }//GEN-LAST:event_btnOrdemDeServicoActionPerformed

    private void btnCompraMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnCompraMouseEntered
        formMouseEntered(evt);
    }//GEN-LAST:event_btnCompraMouseEntered

    private void btnCompraMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnCompraMouseExited
        formMouseExited(evt);
    }//GEN-LAST:event_btnCompraMouseExited

    private void btnCompraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCompraActionPerformed
        MAIN_VIEW.addView(DocumentoEntradaView.getInstance(new Venda(VendaTipo.COMPRA)));
    }//GEN-LAST:event_btnCompraActionPerformed

    private void btnFuncionariosMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnFuncionariosMouseEntered
        formMouseEntered(evt);
    }//GEN-LAST:event_btnFuncionariosMouseEntered

    private void btnFuncionariosMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnFuncionariosMouseExited
        formMouseExited(evt);
    }//GEN-LAST:event_btnFuncionariosMouseExited

    private void btnFuncionariosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFuncionariosActionPerformed
        MAIN_VIEW.addView(FuncionarioListaView.getSingleInstance());
    }//GEN-LAST:event_btnFuncionariosActionPerformed

    private void btnDocumentosEntradaMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnDocumentosEntradaMouseEntered
        formMouseEntered(evt);
    }//GEN-LAST:event_btnDocumentosEntradaMouseEntered

    private void btnDocumentosEntradaMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnDocumentosEntradaMouseExited
        formMouseExited(evt);
    }//GEN-LAST:event_btnDocumentosEntradaMouseExited

    private void btnDocumentosEntradaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDocumentosEntradaActionPerformed
        MAIN_VIEW.addView(DocumentoEntradaListaView.getSingleInstance());
    }//GEN-LAST:event_btnDocumentosEntradaActionPerformed

    private void btnVeiculosMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnVeiculosMouseEntered
        formMouseEntered(evt);
    }//GEN-LAST:event_btnVeiculosMouseEntered

    private void btnVeiculosMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnVeiculosMouseExited
        formMouseExited(evt);
    }//GEN-LAST:event_btnVeiculosMouseExited

    private void btnVeiculosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVeiculosActionPerformed
        MAIN_VIEW.addView(VeiculoListaView.getSingleInstance());
    }//GEN-LAST:event_btnVeiculosActionPerformed

    private void btnDeliveryMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnDeliveryMouseEntered
        formMouseEntered(evt);
    }//GEN-LAST:event_btnDeliveryMouseEntered

    private void btnDeliveryMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnDeliveryMouseExited
        formMouseExited(evt);
    }//GEN-LAST:event_btnDeliveryMouseExited

    private void btnDeliveryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeliveryActionPerformed
        MAIN_VIEW.addView(VendaView.getInstance(new Venda(VendaTipo.DELIVERY)));
    }//GEN-LAST:event_btnDeliveryActionPerformed

    private void btnOSTransporteMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnOSTransporteMouseEntered
        formMouseEntered(evt);
    }//GEN-LAST:event_btnOSTransporteMouseEntered

    private void btnOSTransporteMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnOSTransporteMouseExited
        formMouseExited(evt);
    }//GEN-LAST:event_btnOSTransporteMouseExited

    private void btnOSTransporteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnOSTransporteActionPerformed
         MAIN_VIEW.addView(OSTransporteView.getInstance(new OSTransporte()));
    }//GEN-LAST:event_btnOSTransporteActionPerformed

    private void btnOSsTransporteMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnOSsTransporteMouseEntered
        formMouseEntered(evt);
    }//GEN-LAST:event_btnOSsTransporteMouseEntered

    private void btnOSsTransporteMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnOSsTransporteMouseExited
        formMouseExited(evt);
    }//GEN-LAST:event_btnOSsTransporteMouseExited

    private void btnOSsTransporteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnOSsTransporteActionPerformed
        MAIN_VIEW.addView(OstListaView.getSingleInstance());
    }//GEN-LAST:event_btnOSsTransporteActionPerformed

    private void btnVendaPorFichaMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnVendaPorFichaMouseEntered
        formMouseEntered(evt);
    }//GEN-LAST:event_btnVendaPorFichaMouseEntered

    private void btnVendaPorFichaMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnVendaPorFichaMouseExited
        formMouseExited(evt);
    }//GEN-LAST:event_btnVendaPorFichaMouseExited

    private void btnVendaPorFichaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVendaPorFichaActionPerformed
        MAIN_VIEW.addView(VendaPorFichaView.getSingleInstance());
    }//GEN-LAST:event_btnVendaPorFichaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainMenuView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainMenuView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainMenuView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainMenuView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainMenuView().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBackup;
    private javax.swing.JButton btnCompra;
    private javax.swing.JButton btnDelivery;
    private javax.swing.JButton btnDocumentosEntrada;
    private javax.swing.JButton btnDocumentosSaida;
    private javax.swing.JButton btnFinanceiro;
    private javax.swing.JButton btnFuncionarios;
    private javax.swing.JButton btnMesas;
    private javax.swing.JButton btnOSTransporte;
    private javax.swing.JButton btnOSsTransporte;
    private javax.swing.JButton btnOrcamento;
    private javax.swing.JButton btnOrdemDeServico;
    private javax.swing.JButton btnPessoas;
    private javax.swing.JButton btnProdutos1;
    private javax.swing.JButton btnSistema;
    private javax.swing.JButton btnUsuarios;
    private javax.swing.JButton btnVeiculos;
    private javax.swing.JButton btnVenda;
    private javax.swing.JButton btnVendaPorFicha;
    // End of variables declaration//GEN-END:variables
}
