/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import javax.swing.JOptionPane;
import view.venda.ComandasView;
import view.venda.VendaView;
import javax.swing.plaf.basic.BasicInternalFrameUI;
import model.mysql.bean.principal.documento.Venda;
import model.mysql.bean.principal.documento.VendaTipo;
import static ouroboros.Ouroboros.MENU_MIN_WIDTH;
import static ouroboros.Ouroboros.SCREEN_HEIGHT;
import view.sistema.ConfguracaoSistema;
import static ouroboros.Ouroboros.MAIN_VIEW;
import view.financeiro.FinanceiroContainerView;
import view.funcionario.FuncionarioListaView;
import view.pessoa.PessoaGeralContainerView;
import view.pessoa.PessoaListaView;
import view.produto.geral.ProdutoGeralContainerView;
import view.sistema.BackupView;
import view.sistema.LogAtualizacao;
import view.usuario.UsuarioListaView;
import view.venda.CompraView;
import view.venda.EscolherTipoOrcamento;
import view.venda.geral.VendaGeralContainerView;

/**
 *
 * @author ivand
 */
public class MainMenuView extends javax.swing.JInternalFrame {
    
    
    /**
     * Creates new form MainMenuView
     */
    public MainMenuView() {
        //set apearence
        ((BasicInternalFrameUI)this.getUI()).setNorthPane(null);
        this.setBorder(null);
        this.setBounds(0, 0, MENU_MIN_WIDTH, SCREEN_HEIGHT);
        
        
        
        initComponents();
        
        //btnCompra.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnOrcamento = new javax.swing.JButton();
        btnMesas = new javax.swing.JButton();
        btnVendaLista = new javax.swing.JButton();
        btnProdutos1 = new javax.swing.JButton();
        btnFinanceiro = new javax.swing.JButton();
        btnSistema = new javax.swing.JButton();
        btnPessoas = new javax.swing.JButton();
        btnUsuarios = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        btnBackup = new javax.swing.JButton();
        btnVenda = new javax.swing.JButton();
        btnPedido = new javax.swing.JButton();
        btnOrdemDeServico = new javax.swing.JButton();
        btnLocacao = new javax.swing.JButton();
        btnCompra = new javax.swing.JButton();
        btnLogAtualizacao = new javax.swing.JButton();
        btnFuncionarios = new javax.swing.JButton();

        setBackground(javax.swing.UIManager.getDefaults().getColor("Button.darkShadow"));
        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                formMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                formMouseExited(evt);
            }
        });
        addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentShown(java.awt.event.ComponentEvent evt) {
                formComponentShown(evt);
            }
        });

        btnOrcamento.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        btnOrcamento.setIcon(new javax.swing.ImageIcon(getClass().getResource("/res/img/folder_page_white.png"))); // NOI18N
        btnOrcamento.setText("Orçamento");
        btnOrcamento.setContentAreaFilled(false);
        btnOrcamento.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btnOrcamento.setIconTextGap(20);
        btnOrcamento.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnOrcamentoMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnOrcamentoMouseExited(evt);
            }
        });
        btnOrcamento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnOrcamentoActionPerformed(evt);
            }
        });

        btnMesas.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        btnMesas.setIcon(new javax.swing.ImageIcon(getClass().getResource("/res/img/color_swatch.png"))); // NOI18N
        btnMesas.setText("Comandas");
        btnMesas.setContentAreaFilled(false);
        btnMesas.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btnMesas.setIconTextGap(20);
        btnMesas.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnMesasMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnMesasMouseExited(evt);
            }
        });
        btnMesas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMesasActionPerformed(evt);
            }
        });

        btnVendaLista.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        btnVendaLista.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/resource/img/money.png"))); // NOI18N
        btnVendaLista.setText("Faturamento");
        btnVendaLista.setContentAreaFilled(false);
        btnVendaLista.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btnVendaLista.setIconTextGap(20);
        btnVendaLista.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnVendaListaMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnVendaListaMouseExited(evt);
            }
        });
        btnVendaLista.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVendaListaActionPerformed(evt);
            }
        });

        btnProdutos1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        btnProdutos1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/res/img/package.png"))); // NOI18N
        btnProdutos1.setText("Produtos e Serviços");
        btnProdutos1.setContentAreaFilled(false);
        btnProdutos1.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btnProdutos1.setIconTextGap(20);
        btnProdutos1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnProdutos1MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnProdutos1MouseExited(evt);
            }
        });
        btnProdutos1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnProdutos1ActionPerformed(evt);
            }
        });

        btnFinanceiro.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        btnFinanceiro.setIcon(new javax.swing.ImageIcon(getClass().getResource("/res/img/creditcards.png"))); // NOI18N
        btnFinanceiro.setText("Financeiro");
        btnFinanceiro.setContentAreaFilled(false);
        btnFinanceiro.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btnFinanceiro.setIconTextGap(20);
        btnFinanceiro.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnFinanceiroMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnFinanceiroMouseExited(evt);
            }
        });
        btnFinanceiro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFinanceiroActionPerformed(evt);
            }
        });

        btnSistema.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        btnSistema.setIcon(new javax.swing.ImageIcon(getClass().getResource("/res/img/cog.png"))); // NOI18N
        btnSistema.setText("Sistema");
        btnSistema.setContentAreaFilled(false);
        btnSistema.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btnSistema.setIconTextGap(20);
        btnSistema.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnSistemaMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnSistemaMouseExited(evt);
            }
        });
        btnSistema.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSistemaActionPerformed(evt);
            }
        });

        btnPessoas.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        btnPessoas.setIcon(new javax.swing.ImageIcon(getClass().getResource("/res/img/user.png"))); // NOI18N
        btnPessoas.setText("Clientes e Fornecedores");
        btnPessoas.setContentAreaFilled(false);
        btnPessoas.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btnPessoas.setIconTextGap(20);
        btnPessoas.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnPessoasMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnPessoasMouseExited(evt);
            }
        });
        btnPessoas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPessoasActionPerformed(evt);
            }
        });

        btnUsuarios.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        btnUsuarios.setIcon(new javax.swing.ImageIcon(getClass().getResource("/res/img/key.png"))); // NOI18N
        btnUsuarios.setText("Usuários");
        btnUsuarios.setContentAreaFilled(false);
        btnUsuarios.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btnUsuarios.setIconTextGap(20);
        btnUsuarios.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnUsuariosMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnUsuariosMouseExited(evt);
            }
        });
        btnUsuarios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUsuariosActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel1.setForeground(javax.swing.UIManager.getDefaults().getColor("Button.highlight"));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel1.setText("(19) 3813.2888  99887-4389");

        btnBackup.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        btnBackup.setIcon(new javax.swing.ImageIcon(getClass().getResource("/res/img/disk.png"))); // NOI18N
        btnBackup.setText("Faça Backup diariamente!");
        btnBackup.setContentAreaFilled(false);
        btnBackup.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btnBackup.setIconTextGap(20);
        btnBackup.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnBackupMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnBackupMouseExited(evt);
            }
        });
        btnBackup.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackupActionPerformed(evt);
            }
        });

        btnVenda.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        btnVenda.setIcon(new javax.swing.ImageIcon(getClass().getResource("/res/img/basket.png"))); // NOI18N
        btnVenda.setText("Venda");
        btnVenda.setContentAreaFilled(false);
        btnVenda.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btnVenda.setIconTextGap(20);
        btnVenda.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnVendaMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnVendaMouseExited(evt);
            }
        });
        btnVenda.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVendaActionPerformed(evt);
            }
        });

        btnPedido.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        btnPedido.setIcon(new javax.swing.ImageIcon(getClass().getResource("/res/img/calendar.png"))); // NOI18N
        btnPedido.setText("Pedido (Venda com etapas)");
        btnPedido.setContentAreaFilled(false);
        btnPedido.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btnPedido.setIconTextGap(20);
        btnPedido.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnPedidoMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnPedidoMouseExited(evt);
            }
        });
        btnPedido.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPedidoActionPerformed(evt);
            }
        });

        btnOrdemDeServico.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        btnOrdemDeServico.setIcon(new javax.swing.ImageIcon(getClass().getResource("/res/img/wrench.png"))); // NOI18N
        btnOrdemDeServico.setText("Ordem de Serviço");
        btnOrdemDeServico.setContentAreaFilled(false);
        btnOrdemDeServico.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btnOrdemDeServico.setIconTextGap(20);
        btnOrdemDeServico.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnOrdemDeServicoMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnOrdemDeServicoMouseExited(evt);
            }
        });
        btnOrdemDeServico.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnOrdemDeServicoActionPerformed(evt);
            }
        });

        btnLocacao.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        btnLocacao.setIcon(new javax.swing.ImageIcon(getClass().getResource("/res/img/clock.png"))); // NOI18N
        btnLocacao.setText("Locação");
        btnLocacao.setContentAreaFilled(false);
        btnLocacao.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btnLocacao.setIconTextGap(20);
        btnLocacao.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnLocacaoMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnLocacaoMouseExited(evt);
            }
        });
        btnLocacao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLocacaoActionPerformed(evt);
            }
        });

        btnCompra.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        btnCompra.setIcon(new javax.swing.ImageIcon(getClass().getResource("/res/img/lorry.png"))); // NOI18N
        btnCompra.setText("Compra");
        btnCompra.setContentAreaFilled(false);
        btnCompra.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btnCompra.setIconTextGap(20);
        btnCompra.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnCompraMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnCompraMouseExited(evt);
            }
        });
        btnCompra.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCompraActionPerformed(evt);
            }
        });

        btnLogAtualizacao.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        btnLogAtualizacao.setIcon(new javax.swing.ImageIcon(getClass().getResource("/res/img/information.png"))); // NOI18N
        btnLogAtualizacao.setText("Log de atualizações");
        btnLogAtualizacao.setContentAreaFilled(false);
        btnLogAtualizacao.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btnLogAtualizacao.setIconTextGap(20);
        btnLogAtualizacao.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnLogAtualizacaoMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnLogAtualizacaoMouseExited(evt);
            }
        });
        btnLogAtualizacao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLogAtualizacaoActionPerformed(evt);
            }
        });

        btnFuncionarios.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        btnFuncionarios.setIcon(new javax.swing.ImageIcon(getClass().getResource("/res/img/user_red.png"))); // NOI18N
        btnFuncionarios.setText("Funcionarios");
        btnFuncionarios.setContentAreaFilled(false);
        btnFuncionarios.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btnFuncionarios.setIconTextGap(20);
        btnFuncionarios.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnFuncionariosMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnFuncionariosMouseExited(evt);
            }
        });
        btnFuncionarios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFuncionariosActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(btnMesas, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(btnProdutos1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(btnFinanceiro, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(btnSistema, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(btnPessoas, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(btnUsuarios, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(btnVendaLista, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(btnBackup, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(btnOrcamento, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(btnVenda, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(btnPedido, javax.swing.GroupLayout.DEFAULT_SIZE, 314, Short.MAX_VALUE)
            .addComponent(btnOrdemDeServico, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(btnLocacao, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(btnCompra, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(btnFuncionarios, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(btnLogAtualizacao, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(btnOrcamento)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnVenda)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnPedido)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnOrdemDeServico)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnLocacao)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnCompra)
                .addGap(18, 18, 18)
                .addComponent(btnVendaLista)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnMesas)
                .addGap(18, 18, 18)
                .addComponent(btnProdutos1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnFinanceiro)
                .addGap(4, 4, 4)
                .addComponent(btnPessoas)
                .addGap(4, 4, 4)
                .addComponent(btnFuncionarios)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnSistema)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnUsuarios)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnBackup)
                .addGap(18, 18, 18)
                .addComponent(btnLogAtualizacao)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_formMouseEntered
        this.toFront();
    }//GEN-LAST:event_formMouseEntered

    private void formMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_formMouseExited
        this.toBack();
    }//GEN-LAST:event_formMouseExited

    private void btnOrcamentoMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnOrcamentoMouseEntered
        formMouseEntered(evt);
    }//GEN-LAST:event_btnOrcamentoMouseEntered

    private void btnOrcamentoMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnOrcamentoMouseExited
        formMouseExited(evt);
    }//GEN-LAST:event_btnOrcamentoMouseExited

    private void btnMesasMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnMesasMouseEntered
        formMouseEntered(evt);
    }//GEN-LAST:event_btnMesasMouseEntered

    private void btnMesasMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnMesasMouseExited
        formMouseExited(evt);
    }//GEN-LAST:event_btnMesasMouseExited

    private void btnVendaListaMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnVendaListaMouseEntered
        formMouseEntered(evt);
    }//GEN-LAST:event_btnVendaListaMouseEntered

    private void btnVendaListaMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnVendaListaMouseExited
        formMouseExited(evt);
    }//GEN-LAST:event_btnVendaListaMouseExited

    private void formComponentShown(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_formComponentShown
        
    }//GEN-LAST:event_formComponentShown

    private void btnOrcamentoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnOrcamentoActionPerformed
        EscolherTipoOrcamento escolherTipoOrcamento = new EscolherTipoOrcamento();
    }//GEN-LAST:event_btnOrcamentoActionPerformed

    private void btnVendaListaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVendaListaActionPerformed
        MAIN_VIEW.addView(VendaGeralContainerView.getSingleInstance());
    }//GEN-LAST:event_btnVendaListaActionPerformed

    private void btnMesasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMesasActionPerformed
        MAIN_VIEW.addView(ComandasView.getSingleInstance());
    }//GEN-LAST:event_btnMesasActionPerformed

    private void btnProdutos1MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnProdutos1MouseEntered
        formMouseEntered(evt);
    }//GEN-LAST:event_btnProdutos1MouseEntered

    private void btnProdutos1MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnProdutos1MouseExited
        formMouseExited(evt);
    }//GEN-LAST:event_btnProdutos1MouseExited

    private void btnProdutos1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnProdutos1ActionPerformed
        MAIN_VIEW.addView(ProdutoGeralContainerView.getSingleInstance());
    }//GEN-LAST:event_btnProdutos1ActionPerformed

    private void btnFinanceiroMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnFinanceiroMouseEntered
        formMouseEntered(evt);
    }//GEN-LAST:event_btnFinanceiroMouseEntered

    private void btnFinanceiroMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnFinanceiroMouseExited
        formMouseExited(evt);
    }//GEN-LAST:event_btnFinanceiroMouseExited

    private void btnFinanceiroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFinanceiroActionPerformed
        MAIN_VIEW.addView(FinanceiroContainerView.getSingleInstance());
    }//GEN-LAST:event_btnFinanceiroActionPerformed

    private void btnSistemaMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnSistemaMouseEntered
        formMouseEntered(evt);
    }//GEN-LAST:event_btnSistemaMouseEntered

    private void btnSistemaMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnSistemaMouseExited
        formMouseExited(evt);
    }//GEN-LAST:event_btnSistemaMouseExited

    private void btnSistemaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSistemaActionPerformed
        MAIN_VIEW.addView(ConfguracaoSistema.getSingleInstance());
    }//GEN-LAST:event_btnSistemaActionPerformed

    private void btnPessoasMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnPessoasMouseEntered
        formMouseEntered(evt);
    }//GEN-LAST:event_btnPessoasMouseEntered

    private void btnPessoasMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnPessoasMouseExited
        formMouseExited(evt);
    }//GEN-LAST:event_btnPessoasMouseExited

    private void btnPessoasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPessoasActionPerformed
        MAIN_VIEW.addView(PessoaGeralContainerView.getSingleInstance());
    }//GEN-LAST:event_btnPessoasActionPerformed

    private void btnUsuariosMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnUsuariosMouseEntered
        formMouseEntered(evt);
    }//GEN-LAST:event_btnUsuariosMouseEntered

    private void btnUsuariosMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnUsuariosMouseExited
        formMouseExited(evt);
    }//GEN-LAST:event_btnUsuariosMouseExited

    private void btnUsuariosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUsuariosActionPerformed
        MAIN_VIEW.addView(UsuarioListaView.getSingleInstance());
    }//GEN-LAST:event_btnUsuariosActionPerformed

    private void btnBackupMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnBackupMouseEntered
        formMouseEntered(evt);
    }//GEN-LAST:event_btnBackupMouseEntered

    private void btnBackupMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnBackupMouseExited
        formMouseExited(evt);
    }//GEN-LAST:event_btnBackupMouseExited

    private void btnBackupActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackupActionPerformed
        BackupView b = new BackupView();
    }//GEN-LAST:event_btnBackupActionPerformed

    private void btnVendaMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnVendaMouseEntered
        formMouseEntered(evt);
    }//GEN-LAST:event_btnVendaMouseEntered

    private void btnVendaMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnVendaMouseExited
        formMouseExited(evt);
    }//GEN-LAST:event_btnVendaMouseExited

    private void btnVendaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVendaActionPerformed
        MAIN_VIEW.addView(VendaView.getInstance(new Venda(VendaTipo.VENDA)));
    }//GEN-LAST:event_btnVendaActionPerformed

    private void btnPedidoMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnPedidoMouseEntered
        formMouseEntered(evt);
    }//GEN-LAST:event_btnPedidoMouseEntered

    private void btnPedidoMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnPedidoMouseExited
        formMouseExited(evt);
    }//GEN-LAST:event_btnPedidoMouseExited

    private void btnPedidoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPedidoActionPerformed
        MAIN_VIEW.addView(VendaView.getInstance(new Venda(VendaTipo.PEDIDO)));
    }//GEN-LAST:event_btnPedidoActionPerformed

    private void btnOrdemDeServicoMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnOrdemDeServicoMouseEntered
        formMouseEntered(evt);
    }//GEN-LAST:event_btnOrdemDeServicoMouseEntered

    private void btnOrdemDeServicoMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnOrdemDeServicoMouseExited
        formMouseExited(evt);
    }//GEN-LAST:event_btnOrdemDeServicoMouseExited

    private void btnOrdemDeServicoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnOrdemDeServicoActionPerformed
        MAIN_VIEW.addView(VendaView.getInstance(new Venda(VendaTipo.ORDEM_DE_SERVICO)));
    }//GEN-LAST:event_btnOrdemDeServicoActionPerformed

    private void btnLocacaoMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnLocacaoMouseEntered
        formMouseEntered(evt);
    }//GEN-LAST:event_btnLocacaoMouseEntered

    private void btnLocacaoMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnLocacaoMouseExited
        formMouseExited(evt);
    }//GEN-LAST:event_btnLocacaoMouseExited

    private void btnLocacaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLocacaoActionPerformed
        MAIN_VIEW.addView(VendaView.getInstance(new Venda(VendaTipo.LOCAÇÃO)));
    }//GEN-LAST:event_btnLocacaoActionPerformed

    private void btnCompraMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnCompraMouseEntered
        formMouseEntered(evt);
    }//GEN-LAST:event_btnCompraMouseEntered

    private void btnCompraMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnCompraMouseExited
        formMouseExited(evt);
    }//GEN-LAST:event_btnCompraMouseExited

    private void btnCompraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCompraActionPerformed
        MAIN_VIEW.addView(CompraView.getInstance(new Venda(VendaTipo.COMPRA)));
    }//GEN-LAST:event_btnCompraActionPerformed

    private void btnLogAtualizacaoMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnLogAtualizacaoMouseEntered
        formMouseEntered(evt);
    }//GEN-LAST:event_btnLogAtualizacaoMouseEntered

    private void btnLogAtualizacaoMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnLogAtualizacaoMouseExited
        formMouseExited(evt);
    }//GEN-LAST:event_btnLogAtualizacaoMouseExited

    private void btnLogAtualizacaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLogAtualizacaoActionPerformed
        LogAtualizacao log = new LogAtualizacao();
    }//GEN-LAST:event_btnLogAtualizacaoActionPerformed

    private void btnFuncionariosMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnFuncionariosMouseEntered
        formMouseEntered(evt);
    }//GEN-LAST:event_btnFuncionariosMouseEntered

    private void btnFuncionariosMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnFuncionariosMouseExited
        formMouseExited(evt);
    }//GEN-LAST:event_btnFuncionariosMouseExited

    private void btnFuncionariosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFuncionariosActionPerformed
        MAIN_VIEW.addView(FuncionarioListaView.getSingleInstance());
    }//GEN-LAST:event_btnFuncionariosActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainMenuView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainMenuView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainMenuView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainMenuView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainMenuView().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBackup;
    private javax.swing.JButton btnCompra;
    private javax.swing.JButton btnFinanceiro;
    private javax.swing.JButton btnFuncionarios;
    private javax.swing.JButton btnLocacao;
    private javax.swing.JButton btnLogAtualizacao;
    private javax.swing.JButton btnMesas;
    private javax.swing.JButton btnOrcamento;
    private javax.swing.JButton btnOrdemDeServico;
    private javax.swing.JButton btnPedido;
    private javax.swing.JButton btnPessoas;
    private javax.swing.JButton btnProdutos1;
    private javax.swing.JButton btnSistema;
    private javax.swing.JButton btnUsuarios;
    private javax.swing.JButton btnVenda;
    private javax.swing.JButton btnVendaLista;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
