/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import static ouroboros.Ouroboros.MAIN_VIEW;

/**
 *
 * @author ivand
 */
public class Toast extends javax.swing.JDialog {
    private Long duration = 1000l;
    private boolean autoDismiss = true;
    private String mensagem;
    /**
     * Creates new form Toast
     */
    public Toast(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
    }
    
    public Toast(String mensagem, boolean autoDismiss) {
        super(MAIN_VIEW, true);
        initComponents();
        
        this.mensagem = mensagem;
        this.autoDismiss = autoDismiss;
        
        btnOk.setVisible(true);
        dimensionarJanela();
        
        txtMensagem.setText(mensagem);
        
        this.setVisible(true);
    }
    
    public Toast(String mensagem, Long duration) {
        super(MAIN_VIEW, true);
        initComponents();
        
        this.mensagem = mensagem;
        this.duration = duration;
        
        btnOk.setVisible(false);
        dimensionarJanela();
        
        txtMensagem.setText(mensagem);
        
        this.setVisible(true);
    }
    
    public Toast(String mensagem) {
        super(MAIN_VIEW, true);
        initComponents();
        
        this.mensagem = mensagem;
        
        btnOk.setVisible(false);
        dimensionarJanela();
        
        txtMensagem.setText(mensagem);
        
        this.setVisible(true);
        
    }
    
    
    private void dimensionarJanela() {
        if(mensagem.length() > 40){
            int outraLinha = 0;
            if(mensagem.contains("\r\n")) {
                outraLinha = mensagem.substring(mensagem.indexOf("\r\n")).length();
            }
            int diferenca = (mensagem.length() - outraLinha - 40) * 8;
            int width = this.getWidth() + diferenca;
            this.duration += duration;
            this.setSize(width, this.getHeight());
        }
        
        setLocationRelativeTo(MAIN_VIEW);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnOk = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        txtMensagem = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setResizable(false);
        addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentShown(java.awt.event.ComponentEvent evt) {
                formComponentShown(evt);
            }
        });

        btnOk.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        btnOk.setText("OK");
        btnOk.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnOkActionPerformed(evt);
            }
        });

        txtMensagem.setEditable(false);
        txtMensagem.setBackground(javax.swing.UIManager.getDefaults().getColor("Button.background"));
        txtMensagem.setColumns(20);
        txtMensagem.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        txtMensagem.setRows(5);
        txtMensagem.setMargin(new java.awt.Insets(10, 10, 10, 10));
        jScrollPane2.setViewportView(txtMensagem);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2)
                    .addComponent(btnOk, javax.swing.GroupLayout.DEFAULT_SIZE, 597, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnOk)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formComponentShown(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_formComponentShown
        if(autoDismiss) {
            Long start = System.currentTimeMillis();
            while(true){
                Long elapsed = System.currentTimeMillis() - start;
                if(elapsed >= duration){
                    txtMensagem.setText(elapsed.toString());
                    break;
                }
            }
            dispose();
        }
    }//GEN-LAST:event_formComponentShown

    private void btnOkActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnOkActionPerformed
        dispose();
    }//GEN-LAST:event_btnOkActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Toast.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Toast.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Toast.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Toast.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                Toast dialog = new Toast(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnOk;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextArea txtMensagem;
    // End of variables declaration//GEN-END:variables
}
