/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view.cliente;

import java.awt.Dimension;
import java.awt.event.KeyEvent;
import java.util.List;
import model.bean.principal.Pessoa;
import model.dao.principal.PessoaDAO;
import model.jtable.PessoaJTableModel;
import static ouroboros.Constants.CELL_RENDERER_ALIGN_RIGHT;
import static ouroboros.Ouroboros.MAIN_VIEW;

/**
 *
 * @author ivand
 */
public class PessoaPesquisaView extends javax.swing.JDialog {

    //private static PessoaPesquisaView clientePesquisaView;
    PessoaJTableModel clienteJTableModel = new PessoaJTableModel();
    PessoaDAO clienteDAO = new PessoaDAO();

    List<Pessoa> clientes;
    
    Pessoa cliente = null;

    /**
     * Creates new form ClientePesquisa
     */
    public PessoaPesquisaView() {
        initComponents();

        formatarTabela();
        loadTable();
        
        this.setLocationRelativeTo(MAIN_VIEW);
        this.setModal(true);
        this.setVisible(true);
    }
    
    public Pessoa getCliente(){
        return cliente;
    }
    
    private void formatarTabela() {
        tblClientes.setModel(clienteJTableModel);

        tblClientes.setRowHeight(24);
        tblClientes.setIntercellSpacing(new Dimension(10, 10));
        //id
        tblClientes.getColumnModel().getColumn(0).setPreferredWidth(60);
        tblClientes.getColumnModel().getColumn(0).setCellRenderer(CELL_RENDERER_ALIGN_RIGHT);
        //nome
        tblClientes.getColumnModel().getColumn(1).setPreferredWidth(800);
        //descrição
        tblClientes.getColumnModel().getColumn(2).setPreferredWidth(400);
        //valor
        tblClientes.getColumnModel().getColumn(3).setPreferredWidth(120);
        tblClientes.getColumnModel().getColumn(3).setCellRenderer(CELL_RENDERER_ALIGN_RIGHT);
        //código
        tblClientes.getColumnModel().getColumn(4).setPreferredWidth(200);
        //unidade comercial
        tblClientes.getColumnModel().getColumn(5).setPreferredWidth(120);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txtBuscaRapida = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblClientes = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();

        setTitle("Pesquisar Pessoa");

        txtBuscaRapida.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        txtBuscaRapida.setToolTipText("");
        txtBuscaRapida.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtBuscaRapidaKeyReleased(evt);
            }
        });

        tblClientes.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tblClientes.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                tblClientesFocusGained(evt);
            }
        });
        tblClientes.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblClientesMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblClientes);

        jLabel1.setForeground(java.awt.Color.blue);
        jLabel1.setText("Rolar: PageUp e PageDown | Confirmar: Enter | Cancelar: Esc");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(txtBuscaRapida, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 964, Short.MAX_VALUE))
                        .addContainerGap())))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(txtBuscaRapida, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 402, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel1)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtBuscaRapidaKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtBuscaRapidaKeyReleased
        int index;
        switch (evt.getKeyCode()) {
            case KeyEvent.VK_ESCAPE:
                cliente = null;
                dispose();
                break;
            case KeyEvent.VK_ENTER:
                if(tblClientes.getSelectedRow() != -1) {
                    cliente = clienteJTableModel.getRow(tblClientes.getSelectedRow());
                    dispose();
                }
                break;
            case KeyEvent.VK_DOWN:
                index = tblClientes.getSelectedRow() + 1;
                if (index < tblClientes.getRowCount()) {
                    tblClientes.setRowSelectionInterval(index, index);
                    tblClientes.scrollRectToVisible(tblClientes.getCellRect(index, 0, true));
                }
                break;
            case KeyEvent.VK_UP:
                index = tblClientes.getSelectedRow() - 1;
                if (index > -1) {
                    tblClientes.setRowSelectionInterval(index, index);
                    tblClientes.scrollRectToVisible(tblClientes.getCellRect(index, 0, true));
                }
                break;
            case KeyEvent.VK_PAGE_DOWN:
                index = tblClientes.getSelectedRow() + 10;
                if (index > tblClientes.getRowCount() -1) {
                    index = tblClientes.getRowCount() -1;
                }
                tblClientes.setRowSelectionInterval(index, index);
                tblClientes.scrollRectToVisible(tblClientes.getCellRect(index, 0, true));
                break;
            case KeyEvent.VK_PAGE_UP:
                index = tblClientes.getSelectedRow() - 10;
                if (index < 0) {
                    index = 0;
                }
                tblClientes.setRowSelectionInterval(index, index);
                tblClientes.scrollRectToVisible(tblClientes.getCellRect(index, 0, true));
                break;
            default:
                loadTable();
        }
    }//GEN-LAST:event_txtBuscaRapidaKeyReleased

    private void tblClientesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblClientesMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_tblClientesMouseClicked

    private void tblClientesFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_tblClientesFocusGained
        txtBuscaRapida.requestFocus();
    }//GEN-LAST:event_tblClientesFocusGained


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblClientes;
    private javax.swing.JTextField txtBuscaRapida;
    // End of variables declaration//GEN-END:variables

    private void loadTable() {
        String buscaRapida = txtBuscaRapida.getText();

        clientes = clienteDAO.findByNome(buscaRapida);

        clienteJTableModel.clear();
        clienteJTableModel.addList(clientes);
        
        if(tblClientes.getRowCount() > 0){
            tblClientes.setRowSelectionInterval(0, 0);
        }
    }
}
