/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view.boleto;

import boleto.Boleto;

/**
 *
 * @author ivand
 */
public class BoletoTeste extends javax.swing.JFrame {

    /**
     * Creates new form BoletoTeste
     */
    public BoletoTeste() {
        initComponents();
        
    }
    
    private void calcularDv() {
        
        String dv = Boleto.calcularDv11(txtAgencia.getText(), txtPosto.getText(), txtCedente.getText(), txtAno.getText(), txtByte.getText(), txtSequencial.getText());
        
        txtDv.setText(dv);
    }
    
    private void gerarNossoNumero() {
        txtNossoNumero.setText(Boleto.gerarNossoNumero(txtAno.getText(), txtByte.getText(), txtSequencial.getText(), txtDv.getText()));
        
        txtNossoNumeroFormatado.setText(Boleto.gerarNossoNumeroFormatado(txtAno.getText(), txtByte.getText(), txtSequencial.getText(), txtDv.getText()));
    }

    private void gerarArquivo() {
        ////txtArquivo.setText(Boleto.gerarArquivo());
    }
    
    private void calcularFatorVencimento() {
        txtFatorVencimento.setText(Boleto.calcularFatorVencimento(txtVencimento.getText()));
    }
    
    private void gerarCodigoBarras() {
        txtCodigoBarras.setText(Boleto.gerarCodigoBarras(txtVencimento.getText(), txtValor.getText(), txtNossoNumero.getText(), txtAgencia.getText(), txtPosto.getText(), txtCedente.getText()));
    }
    
    private void gerarLinhaDigitavel() {
        txtLinhaDigitavel.setText(Boleto.gerarLinhaDigitavel(txtCodigoBarras.getText()));
    }
    
    private void calcularDv10() {
        txtDv10.setText(Boleto.calcularDv10(txtCampoDv10.getText()));
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        txtAgencia = new javax.swing.JTextField();
        txtPosto = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        txtCedente = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        txtAno = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        txtByte = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        txtSequencial = new javax.swing.JTextField();
        txtDv = new javax.swing.JTextField();
        btnCalcularDv = new javax.swing.JButton();
        btngerarNossoNumero = new javax.swing.JButton();
        txtNossoNumero = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtArquivo = new javax.swing.JTextArea();
        btnGerarArquivo = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        txtNossoNumeroFormatado = new javax.swing.JTextField();
        btnCalcularDv1 = new javax.swing.JButton();
        txtCodigoBarras = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        txtValor = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        txtVencimento = new javax.swing.JTextField();
        txtFatorVencimento = new javax.swing.JTextField();
        btnCalcularFatorVencimento = new javax.swing.JButton();
        btnGerarLinhaDigitavel = new javax.swing.JButton();
        txtLinhaDigitavel = new javax.swing.JTextField();
        btnDv10 = new javax.swing.JButton();
        jLabel11 = new javax.swing.JLabel();
        txtCampoDv10 = new javax.swing.JTextField();
        txtDv10 = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel1.setText("Agência (4)");

        txtAgencia.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txtAgencia.setText("0718");

        txtPosto.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txtPosto.setText("81");

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel2.setText("Posto (2)");

        txtCedente.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txtCedente.setText("60840");

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel3.setText("Cedente (5)");

        txtAno.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txtAno.setText("20");

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel4.setText("Ano (2)");

        txtByte.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txtByte.setText("1");

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel5.setText("Byte (1)");

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel6.setText("Sequencial");

        txtSequencial.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        txtDv.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        btnCalcularDv.setText("Calcular DV");
        btnCalcularDv.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCalcularDvActionPerformed(evt);
            }
        });

        btngerarNossoNumero.setText("Gerar Nosso Número");
        btngerarNossoNumero.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btngerarNossoNumeroActionPerformed(evt);
            }
        });

        txtNossoNumero.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        txtArquivo.setColumns(20);
        txtArquivo.setRows(5);
        jScrollPane1.setViewportView(txtArquivo);

        btnGerarArquivo.setText("Gerar arquivo");
        btnGerarArquivo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGerarArquivoActionPerformed(evt);
            }
        });

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel7.setText("Limpo");

        jLabel8.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel8.setText("Formatado");

        txtNossoNumeroFormatado.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        btnCalcularDv1.setText("Gerar Código Barras");
        btnCalcularDv1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCalcularDv1ActionPerformed(evt);
            }
        });

        txtCodigoBarras.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        jLabel9.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel9.setText("Valor (8v2)");

        txtValor.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txtValor.setText("99988");

        jLabel10.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel10.setText("Vencimento (DDMMAAAA)");

        txtVencimento.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txtVencimento.setText("03072000");

        txtFatorVencimento.setEditable(false);
        txtFatorVencimento.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        btnCalcularFatorVencimento.setText("Gerar Fator de Vencimento");
        btnCalcularFatorVencimento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCalcularFatorVencimentoActionPerformed(evt);
            }
        });

        btnGerarLinhaDigitavel.setText("Gerar Linha Digitável");
        btnGerarLinhaDigitavel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGerarLinhaDigitavelActionPerformed(evt);
            }
        });

        txtLinhaDigitavel.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        btnDv10.setText("teste dv10");
        btnDv10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDv10ActionPerformed(evt);
            }
        });

        jLabel11.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel11.setText("Campo DV10");

        txtCampoDv10.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txtCampoDv10.setText("748911072");

        txtDv10.setEditable(false);
        txtDv10.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel6)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(txtSequencial, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(jLabel2))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtPosto, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtAgencia, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLabel5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(txtByte, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(txtAno, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jLabel3)
                        .addGap(18, 18, 18)
                        .addComponent(txtCedente, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnCalcularDv)
                        .addGap(18, 18, 18)
                        .addComponent(txtDv))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLabel7)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(txtNossoNumero, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel8)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(txtNossoNumeroFormatado, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(btngerarNossoNumero, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel11)
                        .addGap(18, 18, 18)
                        .addComponent(txtCampoDv10, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnDv10)
                        .addGap(18, 18, 18)
                        .addComponent(txtDv10, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane1)
                            .addComponent(btnGerarArquivo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btnCalcularDv1)
                                .addGap(18, 18, 18)
                                .addComponent(txtCodigoBarras))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btnGerarLinhaDigitavel)
                                .addGap(18, 18, 18)
                                .addComponent(txtLinhaDigitavel))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btnCalcularFatorVencimento)
                                .addGap(18, 18, 18)
                                .addComponent(txtFatorVencimento, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE)))
                        .addContainerGap())
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel9)
                        .addGap(18, 18, 18)
                        .addComponent(txtValor, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel10)
                        .addGap(18, 18, 18)
                        .addComponent(txtVencimento, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(30, 333, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(txtAgencia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(txtPosto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(txtCedente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(txtAno, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(txtByte, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel6)
                            .addComponent(txtSequencial, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 205, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnGerarArquivo)))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnCalcularDv)
                            .addComponent(txtDv, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel10)
                            .addComponent(txtVencimento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel9)
                        .addComponent(txtValor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btngerarNossoNumero)
                            .addComponent(btnCalcularFatorVencimento))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtNossoNumero, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel7)
                            .addComponent(btnCalcularDv1)
                            .addComponent(txtCodigoBarras, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnGerarLinhaDigitavel)
                            .addComponent(txtLinhaDigitavel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(txtFatorVencimento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel11)
                        .addComponent(txtCampoDv10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(txtNossoNumeroFormatado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel8)
                        .addComponent(btnDv10)
                        .addComponent(txtDv10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnCalcularDvActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCalcularDvActionPerformed
        calcularDv();
    }//GEN-LAST:event_btnCalcularDvActionPerformed

    private void btngerarNossoNumeroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btngerarNossoNumeroActionPerformed
        gerarNossoNumero();
    }//GEN-LAST:event_btngerarNossoNumeroActionPerformed

    private void btnGerarArquivoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGerarArquivoActionPerformed
        gerarArquivo();
    }//GEN-LAST:event_btnGerarArquivoActionPerformed

    private void btnCalcularDv1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCalcularDv1ActionPerformed
        gerarCodigoBarras();
    }//GEN-LAST:event_btnCalcularDv1ActionPerformed

    private void btnCalcularFatorVencimentoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCalcularFatorVencimentoActionPerformed
        calcularFatorVencimento();
    }//GEN-LAST:event_btnCalcularFatorVencimentoActionPerformed

    private void btnGerarLinhaDigitavelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGerarLinhaDigitavelActionPerformed
        gerarLinhaDigitavel();
    }//GEN-LAST:event_btnGerarLinhaDigitavelActionPerformed

    private void btnDv10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDv10ActionPerformed
        calcularDv10();
    }//GEN-LAST:event_btnDv10ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(BoletoTeste.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(BoletoTeste.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(BoletoTeste.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(BoletoTeste.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new BoletoTeste().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCalcularDv;
    private javax.swing.JButton btnCalcularDv1;
    private javax.swing.JButton btnCalcularFatorVencimento;
    private javax.swing.JButton btnDv10;
    private javax.swing.JButton btnGerarArquivo;
    private javax.swing.JButton btnGerarLinhaDigitavel;
    private javax.swing.JButton btngerarNossoNumero;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField txtAgencia;
    private javax.swing.JTextField txtAno;
    private javax.swing.JTextArea txtArquivo;
    private javax.swing.JTextField txtByte;
    private javax.swing.JTextField txtCampoDv10;
    private javax.swing.JTextField txtCedente;
    private javax.swing.JTextField txtCodigoBarras;
    private javax.swing.JTextField txtDv;
    private javax.swing.JTextField txtDv10;
    private javax.swing.JTextField txtFatorVencimento;
    private javax.swing.JTextField txtLinhaDigitavel;
    private javax.swing.JTextField txtNossoNumero;
    private javax.swing.JTextField txtNossoNumeroFormatado;
    private javax.swing.JTextField txtPosto;
    private javax.swing.JTextField txtSequencial;
    private javax.swing.JTextField txtValor;
    private javax.swing.JTextField txtVencimento;
    // End of variables declaration//GEN-END:variables
}
