/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view.documentoSaida;

import com.toedter.calendar.JDateChooser;
import java.time.LocalDate;
import java.time.LocalDateTime;
import java.time.LocalTime;
import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;
import javax.swing.JOptionPane;
import javax.swing.JTextField;
import model.mysql.bean.principal.documento.Parcela;
import model.mysql.bean.principal.documento.Venda;
import model.mysql.bean.principal.MovimentoFisico;
import model.mysql.bean.principal.MovimentoFisicoTipo;
import model.mysql.dao.principal.ParcelaDAO;
import model.mysql.dao.principal.MovimentoFisicoDAO;
import model.mysql.dao.principal.VendaDAO;
import static ouroboros.Ouroboros.MAIN_VIEW;
import util.DateTime;
import util.JSwing;
import view.sistema.CalendarioView;

/**
 *
 * @author ivand
 *
 * ESTE FOI CRIADO COMO JDIALOG DESDE O INÍCIO - USAR ESTE COMO REFERÊNCIA PARA
 * OS DEMAIS
 *
 *
 */
public class VendaProcessoView extends javax.swing.JDialog {

    private List<MovimentoFisico> movimentosFisicos = new ArrayList<>();
    private MovimentoFisicoDAO movimentoFisicoDAO = new MovimentoFisicoDAO();
    
    private LocalDateTime andamentoPrevisao;
    private LocalDateTime andamentoReal;
    private LocalDateTime prontoPrevisao;
    private LocalDateTime prontoReal;
    private LocalDateTime entregaPrevisao;
    private LocalDateTime entregaReal;
    
    private VendaProcessoView(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
    }

    public VendaProcessoView(List<MovimentoFisico> movimentosFisicos) {
        super(MAIN_VIEW, true);
        initComponents();
        JSwing.startComponentsBehavior(this);

        this.movimentosFisicos = movimentosFisicos;

        if(movimentosFisicos.isEmpty()) {
            JOptionPane.showMessageDialog(MAIN_VIEW, "Selecione movimentos antes.", "Atenção", JOptionPane.WARNING_MESSAGE);
            dispose();
            
        } else {
            carregarDados();
            
            this.setLocationRelativeTo(this);
            this.setVisible(true);
        }
    }


    private void carregarDados() {
        LocalDateTime entregaPrevisao;
        LocalDateTime entregaReal;
        
        //Date maxDate = list.stream().map(User::getDate).max(Date::compareTo).get();
        //filtrar a maior data
        
        entregaPrevisao = movimentosFisicos.stream().filter(mf -> mf.getDataSaidaPrevista() != null).map(MovimentoFisico::getDataSaidaPrevista).max(LocalDateTime::compareTo).get();
        entregaReal = movimentosFisicos.stream().map(MovimentoFisico::getDataSaida).max(LocalDateTime::compareTo).get();
        
        
        txtEntregaPrevisao.setText(entregaPrevisao.toString());
        txtEntregaReal.setText(entregaReal.toString());
        
    }
    
    private void chamarCalendario(JTextField jTextField) {
        CalendarioView calendario = new CalendarioView();
        jTextField.setText(DateTime.toString(calendario.getDataHora()));
    }


    private void confirmar() {
        andamentoReal = DateTime.fromStringLDT(txtAndamentoReal.getText());
        
        
        for(MovimentoFisico mf : movimentosFisicos) {
            mf.setDataAndamento(andamentoReal);
            mf = movimentoFisicoDAO.save(mf);
            
        }
        
        dispose();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnCancelar = new javax.swing.JButton();
        btnOk = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        btnAndamentoReal = new javax.swing.JButton();
        btnAndamentoPrevisao = new javax.swing.JButton();
        jLabel39 = new javax.swing.JLabel();
        jLabel40 = new javax.swing.JLabel();
        txtAndamentoPrevisao = new javax.swing.JTextField();
        txtAndamentoReal = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        txtProntoPrevisao = new javax.swing.JTextField();
        txtProntoReal = new javax.swing.JTextField();
        btnProntoReal = new javax.swing.JButton();
        btnEntregaReal = new javax.swing.JButton();
        txtEntregaPrevisao = new javax.swing.JTextField();
        txtEntregaReal = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        btnAndamentoReal2 = new javax.swing.JButton();
        btnAndamentoReal3 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Registro de Andamento");
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });

        btnCancelar.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        btnCancelar.setText("Cancelar");
        btnCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelarActionPerformed(evt);
            }
        });

        btnOk.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        btnOk.setText("Ok");
        btnOk.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnOkActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel3.setText("Aguardando");

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel4.setText("Andamento");

        btnAndamentoReal.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        btnAndamentoReal.setIcon(new javax.swing.ImageIcon(getClass().getResource("/res/img/icon/icons8-checkmark-20.png"))); // NOI18N
        btnAndamentoReal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAndamentoRealActionPerformed(evt);
            }
        });

        btnAndamentoPrevisao.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        btnAndamentoPrevisao.setIcon(new javax.swing.ImageIcon(getClass().getResource("/res/img/icon/icons8-timer-20.png"))); // NOI18N
        btnAndamentoPrevisao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAndamentoPrevisaoActionPerformed(evt);
            }
        });

        jLabel39.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel39.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel39.setText("PREVISÃO");
        jLabel39.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jLabel39.setOpaque(true);

        jLabel40.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel40.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel40.setText("REAL");
        jLabel40.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jLabel40.setOpaque(true);

        txtAndamentoPrevisao.setEditable(false);
        txtAndamentoPrevisao.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        txtAndamentoPrevisao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtAndamentoPrevisaoActionPerformed(evt);
            }
        });

        txtAndamentoReal.setEditable(false);
        txtAndamentoReal.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel7.setText("Pronto");

        txtProntoPrevisao.setEditable(false);
        txtProntoPrevisao.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N

        txtProntoReal.setEditable(false);
        txtProntoReal.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N

        btnProntoReal.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        btnProntoReal.setIcon(new javax.swing.ImageIcon(getClass().getResource("/res/img/icon/icons8-checkmark-20.png"))); // NOI18N
        btnProntoReal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnProntoRealActionPerformed(evt);
            }
        });

        btnEntregaReal.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        btnEntregaReal.setIcon(new javax.swing.ImageIcon(getClass().getResource("/res/img/icon/icons8-checkmark-20.png"))); // NOI18N
        btnEntregaReal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEntregaRealActionPerformed(evt);
            }
        });

        txtEntregaPrevisao.setEditable(false);
        txtEntregaPrevisao.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N

        txtEntregaReal.setEditable(false);
        txtEntregaReal.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N

        jLabel8.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel8.setText("Entrega");

        btnAndamentoReal2.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        btnAndamentoReal2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/res/img/icon/icons8-timer-20.png"))); // NOI18N
        btnAndamentoReal2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAndamentoReal2ActionPerformed(evt);
            }
        });

        btnAndamentoReal3.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        btnAndamentoReal3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/res/img/icon/icons8-timer-20.png"))); // NOI18N
        btnAndamentoReal3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAndamentoReal3ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4)
                            .addComponent(jLabel7)
                            .addComponent(jLabel8))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(txtEntregaPrevisao, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 254, Short.MAX_VALUE)
                                    .addComponent(txtProntoPrevisao, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtAndamentoPrevisao, javax.swing.GroupLayout.Alignment.LEADING))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(btnAndamentoPrevisao)
                                    .addComponent(btnAndamentoReal2)
                                    .addComponent(btnAndamentoReal3)))
                            .addComponent(jLabel39, javax.swing.GroupLayout.DEFAULT_SIZE, 313, Short.MAX_VALUE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(txtProntoReal, javax.swing.GroupLayout.DEFAULT_SIZE, 242, Short.MAX_VALUE)
                                    .addComponent(txtEntregaReal))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(btnProntoReal)
                                    .addComponent(btnEntregaReal)))
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                    .addComponent(txtAndamentoReal)
                                    .addGap(18, 18, 18)
                                    .addComponent(btnAndamentoReal))
                                .addComponent(jLabel40, javax.swing.GroupLayout.PREFERRED_SIZE, 313, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(btnCancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(btnOk, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addComponent(jLabel3))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel3)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel39, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel40, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel4)
                        .addComponent(txtAndamentoPrevisao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(btnAndamentoPrevisao)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(btnAndamentoReal)
                        .addComponent(txtAndamentoReal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnProntoReal)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(btnAndamentoReal2)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel7)
                            .addComponent(txtProntoPrevisao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(txtProntoReal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnEntregaReal)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(btnAndamentoReal3)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel8)
                            .addComponent(txtEntregaPrevisao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(txtEntregaReal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnOk)
                    .addComponent(btnCancelar))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
    }//GEN-LAST:event_formWindowClosing

    private void btnOkActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnOkActionPerformed
        confirmar();
    }//GEN-LAST:event_btnOkActionPerformed

    private void btnCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarActionPerformed
        dispose();
    }//GEN-LAST:event_btnCancelarActionPerformed

    private void btnAndamentoRealActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAndamentoRealActionPerformed
        chamarCalendario(txtAndamentoReal);
    }//GEN-LAST:event_btnAndamentoRealActionPerformed

    private void btnAndamentoPrevisaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAndamentoPrevisaoActionPerformed
        chamarCalendario(txtAndamentoPrevisao);
    }//GEN-LAST:event_btnAndamentoPrevisaoActionPerformed

    private void btnProntoRealActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnProntoRealActionPerformed
        chamarCalendario(txtProntoReal);
    }//GEN-LAST:event_btnProntoRealActionPerformed

    private void btnEntregaRealActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEntregaRealActionPerformed
        chamarCalendario(txtEntregaReal);
    }//GEN-LAST:event_btnEntregaRealActionPerformed

    private void btnAndamentoReal2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAndamentoReal2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnAndamentoReal2ActionPerformed

    private void btnAndamentoReal3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAndamentoReal3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnAndamentoReal3ActionPerformed

    private void txtAndamentoPrevisaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtAndamentoPrevisaoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtAndamentoPrevisaoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VendaProcessoView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VendaProcessoView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VendaProcessoView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VendaProcessoView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                VendaProcessoView dialog = new VendaProcessoView(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAndamentoPrevisao;
    private javax.swing.JButton btnAndamentoReal;
    private javax.swing.JButton btnAndamentoReal2;
    private javax.swing.JButton btnAndamentoReal3;
    private javax.swing.JButton btnCancelar;
    private javax.swing.JButton btnEntregaReal;
    private javax.swing.JButton btnOk;
    private javax.swing.JButton btnProntoReal;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel39;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel40;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JTextField txtAndamentoPrevisao;
    private javax.swing.JTextField txtAndamentoReal;
    private javax.swing.JTextField txtEntregaPrevisao;
    private javax.swing.JTextField txtEntregaReal;
    private javax.swing.JTextField txtProntoPrevisao;
    private javax.swing.JTextField txtProntoReal;
    // End of variables declaration//GEN-END:variables
}
