/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view.veiculo;

import java.awt.Dimension;
import java.awt.event.KeyEvent;
import java.util.List;
import model.mysql.bean.principal.Veiculo;
import model.mysql.dao.principal.VeiculoDAO;
import model.jtable.veiculo.VeiculoPesquisaJTableModel;
import static ouroboros.Constants.CELL_RENDERER_ALIGN_RIGHT;
import static ouroboros.Ouroboros.MAIN_VIEW;

/**
 *
 * @author ivand
 */
public class VeiculoPesquisaView extends javax.swing.JDialog {

    //private static VeiculoPesquisaView veiculoPesquisaView;
    VeiculoPesquisaJTableModel veiculoPesquisaJTableModel = new VeiculoPesquisaJTableModel();
    VeiculoDAO veiculoDAO = new VeiculoDAO();

    List<Veiculo> veiculos;
    
    Veiculo veiculo = null;

    public VeiculoPesquisaView() {
        super(MAIN_VIEW, true);
        initComponents();

        formatarTabela();

        carregarTabela();
        
        this.setLocationRelativeTo(MAIN_VIEW);
        this.setVisible(true);
        
    }
    
    public VeiculoPesquisaView(String buscar) {
        super(MAIN_VIEW, true);
        initComponents();

        formatarTabela();

        txtBuscaRapida.setText(buscar);
        carregarTabela();
        
        this.setLocationRelativeTo(MAIN_VIEW);
        this.setVisible(true);
    }
    
    
    public Veiculo getVeiculo(){
        return veiculo;
    }
    
    private void carregarTabela() {
        String buscaRapida = txtBuscaRapida.getText();

        veiculos = veiculoDAO.findByPlacaOuModelo(buscaRapida);

        veiculoPesquisaJTableModel.clear();
        veiculoPesquisaJTableModel.addList(veiculos);
        
        if(tblVeiculo.getRowCount() > 0){
            tblVeiculo.setRowSelectionInterval(0, 0);
        }
    }
    
    private void formatarTabela() {
        tblVeiculo.setModel(veiculoPesquisaJTableModel);

        tblVeiculo.setRowHeight(24);
        tblVeiculo.setIntercellSpacing(new Dimension(10, 10));
        
        tblVeiculo.getColumn("Id").setPreferredWidth(100);
        tblVeiculo.getColumn("Id").setCellRenderer(CELL_RENDERER_ALIGN_RIGHT);
        
        tblVeiculo.getColumn("Placa").setPreferredWidth(800);
        
        tblVeiculo.getColumn("Modelo").setPreferredWidth(400);
        
        tblVeiculo.getColumn("Cor").setPreferredWidth(160);
        
        tblVeiculo.getColumn("Observação").setPreferredWidth(200);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txtBuscaRapida = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblVeiculo = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();

        setTitle("Pesquisar Produto");

        txtBuscaRapida.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        txtBuscaRapida.setToolTipText("");
        txtBuscaRapida.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtBuscaRapidaKeyReleased(evt);
            }
        });

        tblVeiculo.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        tblVeiculo.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tblVeiculo.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                tblVeiculoFocusGained(evt);
            }
        });
        tblVeiculo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblVeiculoMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblVeiculo);

        jLabel1.setForeground(java.awt.Color.blue);
        jLabel1.setText("Rolar: PageUp e PageDown | Confirmar: Enter | Cancelar: Esc");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(txtBuscaRapida, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 980, Short.MAX_VALUE))
                        .addContainerGap())))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(txtBuscaRapida, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 402, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel1)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtBuscaRapidaKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtBuscaRapidaKeyReleased
        int index;
        switch (evt.getKeyCode()) {
            case KeyEvent.VK_ESCAPE:
                veiculo = null;
                dispose();
                break;
            case KeyEvent.VK_ENTER:
                veiculo = veiculoPesquisaJTableModel.getRow(tblVeiculo.getSelectedRow());
                dispose();
                break;
            case KeyEvent.VK_DOWN:
                index = tblVeiculo.getSelectedRow() + 1;
                if (index < tblVeiculo.getRowCount()) {
                    tblVeiculo.setRowSelectionInterval(index, index);
                    tblVeiculo.scrollRectToVisible(tblVeiculo.getCellRect(index, 0, true));
                }
                break;
            case KeyEvent.VK_UP:
                index = tblVeiculo.getSelectedRow() - 1;
                if (index > -1) {
                    tblVeiculo.setRowSelectionInterval(index, index);
                    tblVeiculo.scrollRectToVisible(tblVeiculo.getCellRect(index, 0, true));
                }
                break;
            case KeyEvent.VK_PAGE_DOWN:
                index = tblVeiculo.getSelectedRow() + 10;
                if (index > tblVeiculo.getRowCount() -1) {
                    index = tblVeiculo.getRowCount() -1;
                }
                tblVeiculo.setRowSelectionInterval(index, index);
                tblVeiculo.scrollRectToVisible(tblVeiculo.getCellRect(index, 0, true));
                break;
            case KeyEvent.VK_PAGE_UP:
                index = tblVeiculo.getSelectedRow() - 10;
                if (index < 0) {
                    index = 0;
                }
                tblVeiculo.setRowSelectionInterval(index, index);
                tblVeiculo.scrollRectToVisible(tblVeiculo.getCellRect(index, 0, true));
                break;
            default:
                carregarTabela();
        }
    }//GEN-LAST:event_txtBuscaRapidaKeyReleased

    private void tblVeiculoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblVeiculoMouseClicked
        if(evt.getClickCount() == 2) {
            veiculo = veiculoPesquisaJTableModel.getRow(tblVeiculo.getSelectedRow());
            dispose();
        }
    }//GEN-LAST:event_tblVeiculoMouseClicked

    private void tblVeiculoFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_tblVeiculoFocusGained
        txtBuscaRapida.requestFocus();
    }//GEN-LAST:event_tblVeiculoFocusGained


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblVeiculo;
    private javax.swing.JTextField txtBuscaRapida;
    // End of variables declaration//GEN-END:variables

    
}
